name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    permissions:
      contents: write-all

    runs-on: ubuntu-latest

    env:
      GRADLE_VERSION: '8.4.1' # Ensure compatibility with JDK 21

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Set up Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}

      # Step 4: Build the project
      - name: Build with Gradle Wrapper
        id: gradle-build
        run: |
          ./gradlew build
          export MOD_VERSION_PACKAGE=$(grep '^mod_version=' gradle.properties | cut -d'=' -f2)
          export MOD_NAME=$(grep '^archives_base_name=' gradle.properties | cut -d'=' -f2)
          echo "MOD_VERSION_PACKAGE=$MOD_VERSION_PACKAGE" >> $GITHUB_ENV
          echo "MOD_NAME=$MOD_NAME" >> $GITHUB_ENV

      # Step 5: Upload binaries to release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/libs/${{ env.MOD_NAME }}-${{ env.MOD_VERSION_PACKAGE }}.jar
          asset_name: ${{ env.MOD_NAME }}-Release-${{ github.run_number }}.jar
          tag: Release-${{ github.run_number }}
          overwrite: true
          body: "Automated release by GitHub Actions."

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Submit dependency graph
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
